---
title: "CUP program data analysis"
author: "Noah Willhite"
date: "6/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tm)
library(tidyverse)
library(ggplot2)
library(tm)

getwd()
albidata <- read.table("albifrons.CUP.BubbleData.txt", row.names = NULL, fill = TRUE) %>%
rename(Date = row.names, AMPM = Time, Time = Day)
albidata[is.na(albidata)] = "WideMiss"
albidata$CleanerShoot = removeNumbers(albidata$Shoot)

albitraindata <- read.table("albifrons.CUP.TrainingData.txt", row.names = NULL, fill = TRUE) %>%
rename(Date = row.names, AMPM = Time, Time = Day)

shackdata <- read.table("shackleton.CUP.BubbleData.txt", row.names = NULL, fill = TRUE) %>%
#filter(shackdata$Date != "7/8/2022") %>%
rename(Date = row.names, AMPM = Time, Time = Day)
shackdata[is.na(shackdata)] = "WideMiss"
shackdata$CleanerShoot = removeNumbers(shackdata$Shoot)

volansdata <- read.table("Volans.CUP.BubbleData.txt", row.names = NULL, fill = TRUE) %>%
#filter(shackdata$Date != "7/8/2022") %>%
rename(Date = row.names, AMPM = Time, Time = Day)
volansdata[is.na(volansdata)] = "WideMiss"
volansdata$CleanerShoot = removeNumbers(volansdata$Shoot)

volanstraindata <- read.table("Volans.CUP.TrainingData.txt", row.names = NULL, fill = TRUE) %>%
rename(Date = row.names, AMPM = Time, Time = Day)

bubblelevels <- c("Blue", "Green", "Red", "Black")
```


```{r}
getwd()
albidata <- read.table("albifrons.CUP.BubbleData.txt", row.names = NULL, fill = TRUE) %>%
rename(Date = row.names, AMPM = Time, Time = Day)
albidata[is.na(albidata)] = "WideMiss"
albidata$CleanerShoot = removeNumbers(albidata$Shoot)

shackdata <- read.table("shackleton.CUP.BubbleData.txt", row.names = NULL, fill = TRUE) %>%
rename(Date = row.names, AMPM = Time, Time = Day)
shackdata[is.na(shackdata)] = "WideMiss"
shackdata$CleanerShoot = removeNumbers(shackdata$Shoot)
getwd()

albicorrecteddata <- read.csv(file = "Albicorrecteddata")
```

```{r}
albimisspop <- albidata %>%
  ggplot(aes(x = TestResult))+
  geom_bar(aes(fill = TestResult))
print(albimisspop)

shackmisspop <- shackdata %>%
  ggplot(aes(x = TestResult))+
  geom_bar(aes(fill = TestResult))
print(shackmisspop)
```
Monkey Stats By Date
```{r}
AlbiAccuracyByDate <- albidata %>%
  group_by(Date) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult), undershootprop = sum(CleanerShoot == "Undershoot") / length(CleanerShoot), overshootprop = sum(CleanerShoot == "Overshoot")/ length(CleanerShoot), JackpotAccuracy = sum(TestResult == "Pop" & BColor == "Black")/sum(BColor == "Black"), meanspeed = mean(ActualSpeed))
print(AlbiAccuracyByDate)

ShackAccuracyByDate <- shackdata %>%
  group_by(Date) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult), undershootprop = sum(CleanerShoot == "Undershoot") / length(CleanerShoot), overshootprop = sum(CleanerShoot == "Overshoot")/ length(CleanerShoot), JackpotAccuracy = sum(TestResult == "Pop" & BColor == "Black")/sum(BColor == "Black"), meanspeed = mean(ActualSpeed))
print(ShackAccuracyByDate)

VolansAccuracyByDate <- volansdata %>%
  group_by(Date) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult), undershootprop = sum(CleanerShoot == "Undershoot") / length(CleanerShoot), overshootprop = sum(CleanerShoot == "Overshoot")/ length(CleanerShoot), JackpotAccuracy = sum(TestResult == "Pop" & BColor == "Black")/sum(BColor == "Black"), meanspeed = mean(ActualSpeed))
print(VolansAccuracyByDate)

```
Monkey Stats By Session Number
```{r}
#####################################################################################
AlbiAccuracyBySession <- albidata %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult), undershootprop = sum(CleanerShoot == "Undershoot") / length(CleanerShoot), overshootprop = sum(CleanerShoot == "Overshoot")/ length(CleanerShoot), JackpotAccuracy = sum(TestResult == "Pop" & BColor == "Black")/sum(BColor == "Black"), meanspeed = mean(ActualSpeed)) %>%
  ggplot(aes(x = SessionNumber, y = accuracy, color = "red"))+
  ylim(0,1)+
  geom_point()+
  geom_line()+
  geom_smooth(method = "lm", formula = y~x, se = FALSE)+
  ggtitle("Albifrons Accuracy By Session")
print(AlbiAccuracyBySession)


#####################################################################################
#NOTE, THIS GRAPH IS BAD BECAUSE THE SPEEDVARIABLE CHANGED BETWEEN TRIALS!###########
#####################################################################################
ShackAccuracyBySession <- shackdata %>%
  group_by(SessionNumber, Date) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult), undershootprop = sum(CleanerShoot == "Undershoot") / length(CleanerShoot), overshootprop = sum(CleanerShoot == "Overshoot")/ length(CleanerShoot), JackpotAccuracy = sum(TestResult == "Pop" & BColor == "Black")/sum(BColor == "Black"), meanspeed = mean(ActualSpeed)) %>%
  ggplot(aes(x = SessionNumber, y = accuracy, color = "red"))+
  ylim(0,1)+
  geom_point()+
  geom_line()+
  geom_smooth(method = "lm", formula = y~x, se = FALSE)+
  ggtitle("Shackleton Accuracy By Session")
print(ShackAccuracyBySession)
#####################################################################################
#####################################################################################



```


```{r}

level_order <- c("Blue", "Green", "Red", "Black")
bubblelevels <- factor(level_order, levels = level_order)
ShackAccuracyByBColor <- shackdata %>%
  group_by(BColor) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))%>%
  filter(accuracy >= 0.5 & accuracy <= 0.8) %>%
  ggplot(aes(x=BColor, y = accuracy))+
  geom_point(na.rm = TRUE)+
  geom_line(aes(group = 1), na.rm = TRUE)+
  ylim(0,1)+
  ggtitle("Shackleton Accuracy By Bubble Color")
print(ShackAccuracyByBColor)

se = albidata %>%
  group_by(BColor)%>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult)) %>%
  summarize(se = sd(accuracy)/sqrt(length(accuracy))
            )
  

AlbiAccuracyBySessionNumber <- albidata %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))%>%
  filter(accuracy >= 0.5 & accuracy <= 0.8)
print(AlbiAccuracyBySessionNumber)


##################SEM CALCULATIONS FOR ALBI################
AlbiBlueAccuracyByColor <- albidata %>%
  filter(BColor == "Blue", accuracy) %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
AlbiSEBlue <- sd(AlbiBlueAccuracyByColor$accuracy) / sqrt(length(AlbiBlueAccuracyByColor$accuracy))
AlbiMeanBlueAccuracy <- mean(AlbiBlueAccuracyByColor$accuracy)

AlbiGreenAccuracyByColor <- albidata %>%
  filter(BColor == "Green") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))%>%
AlbiSEGreen <- sd(AlbiGreenAccuracyByColor$accuracy) / sqrt(length(AlbiGreenAccuracyByColor$accuracy))
AlbiMeanGreenAccuracy <- mean(AlbiGreenAccuracyByColor$accuracy)

AlbiRedAccuracyByColor <- albidata %>%
  filter(BColor == "Red") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
AlbiSERed <- sd(AlbiRedAccuracyByColor$accuracy) / sqrt(length(AlbiRedAccuracyByColor$accuracy))
AlbiMeanRedAccuracy <- mean(AlbiRedAccuracyByColor$accuracy)

AlbiBlackAccuracyByColor <- albidata %>%
  filter(BColor == "Black") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
AlbiSEBlack <- sd(AlbiBlackAccuracyByColor$accuracy) / sqrt(length(AlbiBlackAccuracyByColor$accuracy))
AlbiMeanBlackAccuracy <- mean(AlbiBlackAccuracyByColor$accuracy)

AlbiMeanData <- c(AlbiMeanBlueAccuracy, AlbiMeanGreenAccuracy, AlbiMeanRedAccuracy, AlbiMeanBlackAccuracy)
AlbiSE <- c(AlbiSEBlue, AlbiSEGreen, AlbiSERed, AlbiSEBlack)

AlbiDataFrame <- data.frame(bubblelevels, AlbiMeanData)

##########################SHACK SEM CALCULATIONS$##########################
ShackSessionAccuracy <- shackdata %>%
  group_by(SessionNumber) %>% 
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))%>% #Get for each session
  filter(accuracy >=0.5 & accuracy <= .8) #Filter out the sessions where accuracy is outside of this range
ShackSessionIndex <- ShackSessionAccuracy$SessionNumber #Create a vector index of the session numbers within this range.
ShackFinalFiltered <- filter(shackdata, SessionNumber %in% ShackSessionIndex) #Extract the sessions that match the index vector to get the correct observations.


ShackBlueAccuracyByColor <- ShackFinalFiltered %>%
  filter(BColor == "Blue") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
ShackSEBlue <- sd(ShackBlueAccuracyByColor$accuracy) / sqrt(length(ShackBlueAccuracyByColor$accuracy))
ShackMeanBlueAccuracy <- mean(ShackBlueAccuracyByColor$accuracy)

ShackGreenAccuracyByColor <- ShackFinalFiltered %>%
  filter(BColor == "Green") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
ShackSEGreen <- sd(ShackGreenAccuracyByColor$accuracy) / sqrt(length(ShackGreenAccuracyByColor$accuracy))
ShackMeanGreenAccuracy <- mean(ShackGreenAccuracyByColor$accuracy)

ShackRedAccuracyByColor <- ShackFinalFiltered %>%
  filter(BColor == "Red") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
ShackSERed <- sd(ShackRedAccuracyByColor$accuracy) / sqrt(length(ShackRedAccuracyByColor$accuracy))
ShackMeanRedAccuracy <- mean(ShackRedAccuracyByColor$accuracy)

ShackBlackAccuracyByColor <- ShackFinalFiltered %>%
  filter(BColor == "Black") %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
ShackSEBlack <- sd(ShackBlackAccuracyByColor$accuracy) / sqrt(length(ShackBlackAccuracyByColor$accuracy))
ShackMeanBlackAccuracy <- mean(ShackBlackAccuracyByColor$accuracy)

level_order <- c("Blue", "Green", "Red", "Black")
bubblelevels <- factor(level_order, levels = level_order)
ShackMeanData <- c(ShackMeanBlueAccuracy, ShackMeanGreenAccuracy, ShackMeanRedAccuracy, ShackMeanBlackAccuracy)
ShackSE <- c(ShackSEBlue, ShackSEGreen, ShackSERed, ShackSEBlack)

ShackDataFrame <- data.frame(bubblelevels, ShackMeanData)


################FIGURES FOR SURE POSTER#####################
AlbiSUREgraph <- AlbiDataFrame %>%
  ggplot(aes(x = bubblelevels, y = AlbiMeanData))+
  geom_point()+
  geom_line(aes(group = 1), na.rm = TRUE)+
  ylim(0.5,0.8)+
  geom_errorbar(aes(ymin=AlbiMeanData-AlbiSE, ymax=AlbiMeanData+AlbiSE), width=0.2, colour="black", alpha=1, size=.5)+
  scale_x_discrete(limits = bubblelevels)+
  theme_classic()
print(AlbiSUREgraph)

###########################ALBIGRAPH######################################
AlbiAccuracyByBColor <- albidata %>%
  filter(Date == "7/22/2022")%>%
  group_by(BColor) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))%>%
  ggplot(aes(x=factor(BColor, level = level_order), y = mean(accuracy))) +
  geom_point(na.rm = TRUE)+
  geom_line(aes(group = 1), na.rm = TRUE)+
  ylim(0,0.8)+
  ggtitle("Albifrons Accuracy By Bubble Color")+
  labs(x = "Bubble Color", y = "Accuracy")+
  theme_classic()
print(AlbiAccuracyByBColor)


ShackSUREgraph <- ShackDataFrame %>%
  ggplot(aes(x = bubblelevels, y = ShackMeanData), width = 1)+
  geom_point(aes(size = 1, col = bubblelevels))+
  scale_color_manual(values = c("blue", "green", "red", "black"))+
  geom_line(aes(group = 1), na.rm = TRUE, size = 1)+
  ylim(0.5,0.8)+
  geom_errorbar(aes(ymin=ShackMeanData-ShackSE, ymax=ShackMeanData+ShackSE), width=0.2, colour="black", alpha=1, size=1)+
  geom_point()+
  scale_x_discrete(limits = bubblelevels)+
  theme_classic()+
  theme(axis.text=element_text(size = 15), axis.title = element_text(size = 15), legend.position = "none", plot.title = element_text(size = 20))+
  ggtitle("Shackleton Motor Task Performance (21 Sessions)")+
  labs(x = "Bubble Color", y = "Accuracy")
print(ShackSUREgraph)



#Random collapsed across x axis graph



```


TEMP albidata
```{r}
Albimeans<- Albicorrecteddata %>%
  group_by(Color) %>%
  summarize(averageaccuracy = mean(x))

AlbiBlack <- Albicorrecteddata %>%
  filter(Color == "Black") 
AlbiSEBlack <- sd(AlbiBlack$Average) / sqrt(length(AlbiBlack$Average))
print(AlbiSEBlack)

AlbiBlue <- Albicorrecteddata %>%
  filter(Color == "Blue") 
AlbiSEBlue <- sd(AlbiBlue$Average) / sqrt(length(AlbiBlue$Average))
print(AlbiSEBlue)

AlbiRed <- Albicorrecteddata %>%
filter(Color == "Red") 
AlbiSERed <- sd(AlbiRed$Average) / sqrt(length(AlbiRed$Average))
print(AlbiSERed)

AlbiGreen <- Albicorrecteddata %>%
  filter(Color == "Green") 
AlbiSEGreen <- sd(AlbiGreen$Average) / sqrt(length(AlbiGreen$Average))
print(AlbiSEGreen)

AlbiMeanGreen <- mean(AlbiGreen$Average)
AlbiMeanBlack <- mean(AlbiBlack$Average)
AlbiMeanRed <- mean(AlbiRed$Average)
AlbiMeanBlue <- mean(AlbiBlue$Average)


level_order <- c("Blue", "Green", "Red", "Black")
bubblelevels <- factor(level_order, levels = level_order)

SEDF<- c(AlbiSEBlue, AlbiSEGreen, AlbiSERed, AlbiSEBlack)
AlbiMeanVector <- c(AlbiMeanBlue, AlbiMeanGreen, AlbiMeanRed, AlbiMeanBlack)
AlbiTempDF <- data.frame(bubblelevels, AlbiMeanVector)

AlbiNEWSUREgraph <- AlbiTempDF %>%
  ggplot(aes(x = bubblelevels, y = AlbiMeanVector, size = 1))+
  geom_point(aes(size = 1, col = bubblelevels))+
  scale_color_manual(values = c("blue", "green", "red", "black"))+
  geom_line(aes(group = 1), na.rm = TRUE, size = 1)+
  ylim(0.5,0.8)+
  geom_errorbar(aes(ymin=AlbiMeanVector-SEDF, ymax=AlbiMeanVector+SEDF), width=0.2, colour="black", alpha=1, size=0.8)+
  scale_x_discrete(limits = bubblelevels)+
  theme_classic()+
  theme(axis.text=element_text(size = 15), axis.title = element_text(size = 15), legend.position = "none", plot.title = element_text(size = 20))+
  ggtitle("Albifrons Motor Task Performance (98 Sessions)")+
  labs(x = "Bubble Color", y = "Accuracy")
print(AlbiNEWSUREgraph)


```


RUN ANOVA/ TUKEY HSD TEST
```{r}
AlbiANOVA <- aov(Albicorrecteddata$Average~Albicorrecteddata$Color)
summary(AlbiANOVA)

#Run TUKEYHSD
TukeyHSD(AlbiANOVA, conf.level = 0.95) #Red and Blak are n.s according to Tukeys, but this is more conservative than 2 sample so idk. Ask rael or jad.


ShackANOVADS <- ShackFinalFiltered %>%
  group_by(BColor, SessionNumber) %>%
  summarize(accuracy = sum(TestResult == "Pop") / length(TestResult))
ShackANOVA <- aov(ShackANOVADS$accuracy~ShackANOVADS$BColor)
summary(ShackANOVA)

TukeyHSD(ShackANOVA, conf.level = 0.95)

```


UNPAIRED 2-Sample T-Test
```{r}
#Getmeans
AlbiRed <- Albicorrecteddata %>%
  filter(Color == "Red") 
AlbiMeanRed <- mean(AlbiRed$Average)

AlbiBlack <- Albicorrecteddata %>%
  filter(Color == "Black") 
AlbiMeanBlack <- mean(AlbiBlack$Average)

t.test(AlbiBlack$Average, AlbiRed$Average, var.equal = TRUE, alternative = ("less"))

ShackRed <- Shackcorrecteddata %>%
  filter(BColor == "Red") 
ShackMeanRed <- mean(ShackRed$accuracy)

ShackBlack <- Shackcorrecteddata %>%
  filter(BColor == "Black") 
ShackMeanBlack <- mean(ShackBlack$accuracy)

t.test(ShackRed$accuracy, ShackBlack$accuracy, var.equal = TRUE, alternative = ("less"))
  
  
```
Training Data Analysis

```{r}
albitraindata %>%
  group_by(Date) %>%
  summarize(accuracy = sum(Correct == 1) / length(Correct))

volanstraindata %>%
  group_by(SessionNumber) %>%
  summarize(accuracy = sum(Correct == 1)/ length(Correct))

shacktraindata %>%
  group_by(Phase) %>%
  summarize(accuracy = sum(Correct == 1)/ length(Correct)) %>%
  ggplot(aes(x = Phase, y = accuracy))+
  geom_point()

```

Number of Pellets
```{r}
albitraindata %>%
  filter(Date == "7/27/2022", Correct == 1) %>%
  group_by(CorrectChoice)%>%
  summarize(sum = sum(Correct == 1))
  
```


Cue latency by bubble color

```{r}
albidata %>%
  group_by(BColor) %>%
  summarize(AverageCueLatency = median(CueLatency))

shackdata %>%
  group_by(BColor) %>%
  summarize(AverageCueLatency = median(CueLatency))
```

Overshoot/Undershoot
```{r}
albidata$Date <- gsub("/", "", as.character(albidata$Date))
valid_column_names <- make.names(names=names(albidata$Date), unique=TRUE, allow_ = TRUE)
names(albidata$Date) <- valid_column_names

albidata %>%
  group_by(Shoot) %>%
  mutate(CleanShoot = removeNumbers(Shoot))%>%
  ggplot(aes(x = CleanShoot))+
  geom_bar(position = "dodge")

shackdata %>%
  group_by(Shoot) %>%
  mutate(CleanShoot = removeNumbers(Shoot))%>%
  ggplot(aes(x = CleanShoot))+
  geom_bar(position = "dodge")
```
Fun Graphs
```{r}

```

